services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports: 
      - 5432:5432
    volumes:
      - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./config/postgresql.conf:/etc/postgresql/postgresql.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "200MB"

  api01: &api
    build: .
    container_name: api01
    ports:
      - 3000:3000
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          cpus: "0.55"
          memory: "120MB"
  
  api02:
    <<: *api
    container_name: api02
    ports:
      - 3001:3000

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 9999:9999
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "80MB"